---
# Variables for the web server configuration

# Ethernet interface on which the web server should listen.
# Defaults to the first interface. Change this to:
#
#  iface: eth1
#
# ...to override.
#
iface: '{{ ansible_default_ipv4.interface }}'

# this is the repository that holds our sample webapp
#repository: "git@github.com:nicolas-g/demo-app.git"
repository: https://github.com/nicolas-g/demo-app.git
